//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdullahWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadMachine
    {
        public int Id { get; set; }
        public Nullable<int> MC { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> Buyer { get; set; }
        public string Order { get; set; }
        public string Colour { get; set; }
        public string ColourAvater { get; set; }
        public string Fabric { get; set; }
        public Nullable<int> FinishType { get; set; }
        public string Matching { get; set; }
        public string BatchType { get; set; }
        public Nullable<int> RemarksAndPrecautions { get; set; }
        public Nullable<bool> FabricStock { get; set; }
        public Nullable<bool> ColourStock { get; set; }
        public Nullable<bool> PlanConfirm { get; set; }
        public string TOQ { get; set; }
        public Nullable<int> OrderCode { get; set; }
        public string ColourSequence { get; set; }
    
        public virtual BuyerInfo BuyerInfo { get; set; }
        public virtual FinishInfo FinishInfo { get; set; }
        public virtual RemarksInfo RemarksInfo { get; set; }
        public virtual OrderCodeInfo OrderCodeInfo { get; set; }
    }
}
