//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdullahWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MachineDBEntities : DbContext
    {
        public MachineDBEntities()
            : base("name=MachineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuyerInfo> BuyerInfoes { get; set; }
        public virtual DbSet<FinishInfo> FinishInfoes { get; set; }
        public virtual DbSet<LoadMachine> LoadMachines { get; set; }
        public virtual DbSet<OrderCodeInfo> OrderCodeInfoes { get; set; }
        public virtual DbSet<RemarksInfo> RemarksInfoes { get; set; }
    }
}
