//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdullahWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemarksInfo
    {
        public RemarksInfo()
        {
            this.LoadMachines = new HashSet<LoadMachine>();
        }
    
        public int Id { get; set; }
        public string RemarksName { get; set; }
    
        public virtual ICollection<LoadMachine> LoadMachines { get; set; }
    }
}
